version: "3.7"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-RC1-ubuntu
    ports:
      - "10000:1433"
    environment:
      SA_PASSWORD: "HacerDevelopment2019"
      ACCEPT_EULA: "Y"
  api-server:
    image: node:10.16-buster
    ports:
      - "10001:8080"
    volumes:
      - type: bind
        source: "${REPOS_ROOT}/hacer"
        target: /opt/hacer/
    stdin_open: true
    tty: true